name: GitHub Actions Pr Review
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issues:
    types: [opened, edited]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install axios
      - name: Review PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const axios = require('axios');
          const githubToken = process.env.GITHUB_TOKEN;
          const prNumber = process.env.GITHUB_EVENT.pull_request.number;
          const repo = process.env.GITHUB_REPOSITORY;
          const [owner, repoName] = repo.split('/');

          async function getPullRequestFiles() {
            const url = `https://api.github.com/repos/${owner}/${repoName}/pulls/${prNumber}/files`;
            const response = await axios.get(url, {
              headers: {
                Authorization: `token ${githubToken}`
              }
            });
            return response.data;
          }

          async function commentOnPullRequest(body) {
            const url = `https://api.github.com/repos/${owner}/${repoName}/issues/${prNumber}/comments`;
            await axios.post(url, { body }, {
              headers: {
                Authorization: `token ${githubToken}`
              }
            });
          }

          (async () => {
            const files = await getPullRequestFiles();
            for (const file of files) {
              const body = `Changes in \`${file.filename}\`:\n\n\`\`\`${file.patch}\`\`\``;
              await commentOnPullRequest(body);
            }
          })();
